---
title: "covid19AnalysisGraphicRep"
author: "Jummie"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
covid.data <- read.csv("~/R/archive/covid-data.csv")
#Is there an impact of covid on Country's gdp?
#Using scatter plot
plot_ <- ggplot(covid.data, aes(x=total_cases, y=gdp_per_capita))+geom_point()+
  labs(title = "Relationship between Total Covid Cases and the Country's GDP",
       xlab="Total Cases", ylab="GDP")
plot_ #From the plot, the higher the covid cases, the lesser the gdp
```

```{r}
boxplot(total_cases~life_expectancy, data = covid.data, main="Boxplot of Life Expectancy based on Covid_19 2020 Total Cases")
```
```{r}
boxplot(total_cases~human_development_index, data = covid.data, main="Boxplot of Human Development Index based on Covid_19 2020 Total Cases")
```

```{r}
hist(covid.data$reproduction_rate, xlab = "Reproduction Rate", main = "Histogram of Reproduction Rate during Covid_19")
#This shows that an Increase in Covid_19 Total Cases brought about a Decrease in Reproduction.
```

